# Site settings
<<<<<<< HEAD
title: Nithin Krishna
description: 'My Simple BLog'
#url: 'http://joshgerdes.com/jekyll-uno'
=======
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno'
>>>>>>> b9df394d7e0583e12c50a717e52adad57f4563cd
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Nithin Krishna'
  email: nithin.krishna@outlook.com

  github_username:  nitkna
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
